import { formatReference } from "../../core/output-formatter.js";
import type { CommandEntry, McpToolEntry } from "../../core/output-formatter.js";
import type { OutputFormat } from "../../models/types.js";

/**
 * Hardcoded registry of all CLI commands and MCP tools.
 * A drift-detection test verifies this stays in sync with actual registrations.
 */

export type { CommandEntry, McpToolEntry };

export const COMMANDS: readonly CommandEntry[] = [
  {
    name: "init",
    description: "Initialize a new .story/ project",
    usage: "storybloq init [--name <name>] [--type <type>] [--language <lang>] [--force] [--format json|md]",
    flags: ["--name", "--type", "--language", "--force"],
  },
  {
    name: "status",
    description: "Project summary: phase statuses, ticket/issue counts, blockers",
    usage: "storybloq status [--format json|md]",
  },
  {
    name: "ticket list",
    description: "List tickets with optional filters",
    usage: "storybloq ticket list [--status <s>] [--phase <p>] [--type <t>] [--format json|md]",
    flags: ["--status", "--phase", "--type"],
  },
  {
    name: "ticket get",
    description: "Get ticket details by ID",
    usage: "storybloq ticket get <id> [--format json|md]",
  },
  {
    name: "ticket next",
    description: "Suggest next ticket(s) to work on",
    usage: "storybloq ticket next [--count N] [--format json|md]",
  },
  {
    name: "ticket blocked",
    description: "List blocked tickets with their blocking dependencies",
    usage: "storybloq ticket blocked [--format json|md]",
  },
  {
    name: "ticket create",
    description: "Create a new ticket",
    usage: "storybloq ticket create --title <t> --type <type> [--phase <p>] [--description <d>] [--blocked-by <ids>] [--parent-ticket <id>] [--format json|md]",
    flags: ["--title", "--type", "--phase", "--description", "--blocked-by", "--parent-ticket"],
  },
  {
    name: "ticket update",
    description: "Update a ticket",
    usage: "storybloq ticket update <id> [--status <s>] [--title <t>] [--type <type>] [--phase <p>] [--order <n>] [--description <d>] [--blocked-by <ids>] [--parent-ticket <id>] [--format json|md]",
    flags: ["--status", "--title", "--type", "--phase", "--order", "--description", "--blocked-by", "--parent-ticket"],
  },
  {
    name: "ticket meta",
    description: "Get, set, or unset custom passthrough metadata on a ticket",
    usage: "storybloq ticket meta get|set|unset <id> [path] [value] [--format json|md]",
  },
  {
    name: "ticket delete",
    description: "Delete a ticket",
    usage: "storybloq ticket delete <id> [--force] [--format json|md]",
    flags: ["--force"],
  },
  {
    name: "issue list",
    description: "List issues with optional filters",
    usage: "storybloq issue list [--status <s>] [--severity <sev>] [--component <c>] [--phase <p>] [--format json|md]",
    flags: ["--status", "--severity", "--component", "--phase"],
  },
  {
    name: "issue get",
    description: "Get issue details by ID",
    usage: "storybloq issue get <id> [--format json|md]",
  },
  {
    name: "issue create",
    description: "Create a new issue",
    usage: "storybloq issue create --title <t> --severity <s> --impact <i> [--components <c>] [--related-tickets <ids>] [--location <locs>] [--phase <p>] [--format json|md]",
    flags: ["--title", "--severity", "--impact", "--components", "--related-tickets", "--location", "--phase"],
  },
  {
    name: "issue update",
    description: "Update an issue",
    usage: "storybloq issue update <id> [--status <s>] [--title <t>] [--severity <sev>] [--impact <i>] [--resolution <r>] [--components <c>] [--related-tickets <ids>] [--location <locs>] [--order <n>] [--phase <p>] [--format json|md]",
    flags: ["--status", "--title", "--severity", "--impact", "--resolution", "--components", "--related-tickets", "--location", "--order", "--phase"],
  },
  {
    name: "issue meta",
    description: "Get, set, or unset custom passthrough metadata on an issue",
    usage: "storybloq issue meta get|set|unset <id> [path] [value] [--format json|md]",
  },
  {
    name: "issue delete",
    description: "Delete an issue",
    usage: "storybloq issue delete <id> [--format json|md]",
  },
  {
    name: "phase list",
    description: "List all phases with derived status",
    usage: "storybloq phase list [--format json|md]",
  },
  {
    name: "phase current",
    description: "Show current (first non-complete) phase",
    usage: "storybloq phase current [--format json|md]",
  },
  {
    name: "phase tickets",
    description: "List tickets in a specific phase",
    usage: "storybloq phase tickets --phase <id> [--format json|md]",
    flags: ["--phase"],
  },
  {
    name: "phase create",
    description: "Create a new phase",
    usage: "storybloq phase create --id <id> --name <n> --label <l> --description <d> [--summary <s>] [--after <id>] [--at-start] [--format json|md]",
    flags: ["--id", "--name", "--label", "--description", "--summary", "--after", "--at-start"],
  },
  {
    name: "phase rename",
    description: "Rename/update phase metadata",
    usage: "storybloq phase rename <id> [--name <n>] [--label <l>] [--description <d>] [--summary <s>] [--format json|md]",
    flags: ["--name", "--label", "--description", "--summary"],
  },
  {
    name: "phase move",
    description: "Move a phase to a new position",
    usage: "storybloq phase move <id> [--after <id>] [--at-start] [--format json|md]",
    flags: ["--after", "--at-start"],
  },
  {
    name: "phase delete",
    description: "Delete a phase",
    usage: "storybloq phase delete <id> [--reassign <phase-id>] [--format json|md]",
    flags: ["--reassign"],
  },
  {
    name: "handover list",
    description: "List handover filenames (newest first)",
    usage: "storybloq handover list [--format json|md]",
  },
  {
    name: "handover latest",
    description: "Content of most recent handover",
    usage: "storybloq handover latest [--format json|md]",
  },
  {
    name: "handover get",
    description: "Content of a specific handover",
    usage: "storybloq handover get <filename> [--format json|md]",
  },
  {
    name: "handover create",
    description: "Create a new handover document",
    usage: "storybloq handover create [--content <md>] [--stdin] [--slug <slug>] [--format json|md]",
    flags: ["--content", "--stdin", "--slug"],
  },
  {
    name: "blocker list",
    description: "List all roadmap blockers",
    usage: "storybloq blocker list [--format json|md]",
  },
  {
    name: "blocker add",
    description: "Add a new blocker",
    usage: "storybloq blocker add --name <n> [--note <note>] [--format json|md]",
    flags: ["--name", "--note"],
  },
  {
    name: "blocker clear",
    description: "Clear (resolve) a blocker",
    usage: "storybloq blocker clear --name <n> [--note <note>] [--format json|md]",
    flags: ["--name", "--note"],
  },
  {
    name: "note list",
    description: "List notes with optional status/tag filters",
    usage: "storybloq note list [--status <s>] [--tag <t>] [--format json|md]",
    flags: ["--status", "--tag"],
  },
  {
    name: "note get",
    description: "Get a note by ID",
    usage: "storybloq note get <id> [--format json|md]",
  },
  {
    name: "note create",
    description: "Create a new note",
    usage: "storybloq note create --content <c> [--title <t>] [--tags <tags>] [--format json|md]",
    flags: ["--content", "--title", "--tags"],
  },
  {
    name: "note update",
    description: "Update a note",
    usage: "storybloq note update <id> [--content <c>] [--title <t>] [--tags <tags>] [--clear-tags] [--status <s>] [--format json|md]",
    flags: ["--content", "--title", "--tags", "--clear-tags", "--status"],
  },
  {
    name: "note delete",
    description: "Delete a note",
    usage: "storybloq note delete <id> [--format json|md]",
  },
  {
    name: "lesson list",
    description: "List lessons with optional status/tag/source filters",
    usage: "storybloq lesson list [--status <s>] [--tag <t>] [--source <src>] [--format json|md]",
    flags: ["--status", "--tag", "--source"],
  },
  {
    name: "lesson get",
    description: "Get a lesson by ID",
    usage: "storybloq lesson get <id> [--format json|md]",
  },
  {
    name: "lesson digest",
    description: "Ranked digest of active lessons for context loading",
    usage: "storybloq lesson digest [--format json|md]",
  },
  {
    name: "lesson create",
    description: "Create a new lesson",
    usage: "storybloq lesson create --title <t> --content <c> --context <ctx> --source <src> [--tags <tags>] [--supersedes <id>] [--format json|md]",
    flags: ["--title", "--content", "--context", "--source", "--tags", "--supersedes"],
  },
  {
    name: "lesson update",
    description: "Update a lesson",
    usage: "storybloq lesson update <id> [--title <t>] [--content <c>] [--context <ctx>] [--tags <tags>] [--status <s>] [--supersedes <id>] [--format json|md]",
    flags: ["--title", "--content", "--context", "--tags", "--status", "--supersedes"],
  },
  {
    name: "lesson reinforce",
    description: "Reinforce a lesson: increment count and update lastValidated",
    usage: "storybloq lesson reinforce <id> [--format json|md]",
  },
  {
    name: "lesson delete",
    description: "Delete a lesson",
    usage: "storybloq lesson delete <id> [--hard] [--format json|md]",
    flags: ["--hard"],
  },
  {
    name: "validate",
    description: "Reference integrity + schema checks on all .story/ files",
    usage: "storybloq validate [--format json|md]",
  },
  {
    name: "snapshot",
    description: "Save current project state for session diffs",
    usage: "storybloq snapshot [--quiet] [--format json|md]",
    flags: ["--quiet"],
  },
  {
    name: "recap",
    description: "Session diff — changes since last snapshot + suggested actions",
    usage: "storybloq recap [--format json|md]",
  },
  {
    name: "export",
    description: "Self-contained project document for sharing",
    usage: "storybloq export [--phase <id>] [--all] [--format json|md]",
    flags: ["--phase", "--all"],
  },
  {
    name: "recommend",
    description: "Context-aware work suggestions",
    usage: "storybloq recommend [--count N] [--format json|md]",
  },
  {
    name: "reference",
    description: "Print CLI command and MCP tool reference",
    usage: "storybloq reference [--format json|md]",
  },
  {
    name: "selftest",
    description: "Run integration smoke test — create/update/delete cycle across all entity types",
    usage: "storybloq selftest [--format json|md]",
  },
  {
    name: "codex-review",
    description: "Run native Codex plan or code review for an autonomous session",
    usage: "storybloq codex-review plan|code --session <id> --format guide-report",
    flags: ["--session", "--format"],
  },
  {
    name: "setup",
    description: "Install Storybloq skill, MCP, and hooks for Claude, Codex, or both",
    usage: "storybloq setup [--client claude|codex|all] [--skip-hooks]",
    flags: ["--client", "--skip-hooks"],
  },
  {
    name: "setup-skill",
    description: "Compatibility alias for `storybloq setup --client claude`",
    usage: "storybloq setup-skill [--skip-hooks]",
    flags: ["--skip-hooks"],
  },
  {
    name: "reconcile",
    description: "Detect and fix duplicate displayIds across all entity types",
    usage: "storybloq reconcile [--dry-run] [--ci] [--rebalance-ranks] [--format json|md]",
    flags: ["--dry-run", "--ci", "--rebalance-ranks"],
  },
  {
    name: "conflicts list",
    description: "List all items with unresolved merge conflicts",
    usage: "storybloq conflicts list [--format json|md]",
  },
  {
    name: "conflicts show",
    description: "Show field-level conflict detail for an item",
    usage: "storybloq conflicts show <id> [--format json|md]",
  },
  {
    name: "resolve",
    description: "Resolve merge conflicts on a .story/ item",
    usage: "storybloq resolve <id> [--field <f>] [--use ours|theirs] [--value <json>] [--format json|md]",
    flags: ["--field", "--use", "--value"],
  },
  {
    name: "merge-driver",
    description: "Git merge driver for .story/ JSON files (registered via team setup)",
    usage: "storybloq merge-driver <ancestor> <ours> <theirs> <pathname>",
  },
  {
    name: "team init",
    description: "Enable team mode on this project",
    usage: "storybloq team init [--claim-staleness-hours N] [--id-allocator local|git-refs] [--format json|md]",
    flags: ["--claim-staleness-hours", "--id-allocator"],
  },
  {
    name: "team setup",
    description: "Install the git merge driver and .gitattributes for team mode",
    usage: "storybloq team setup [--format json|md]",
  },
  {
    name: "team doctor",
    description: "Run team health checks on the project",
    usage: "storybloq team doctor [--ci] [--format json|md]",
    flags: ["--ci"],
  },
  {
    name: "team reserve",
    description: "Reserve display IDs via remote git refs",
    usage: "storybloq team reserve <type> [--count N] [--format json|md]",
    flags: ["--count"],
  },
  {
    name: "team config",
    description: "Show or set team configuration",
    usage: "storybloq team config get|set [key] [value] [--format json|md]",
  },
  {
    name: "gc",
    description: "Remove tombstoned files past retention period",
    usage: "storybloq gc [--apply] [--force] [--retention-days N] [--format json|md]",
    flags: ["--apply", "--force", "--retention-days"],
  },
  {
    name: "repair",
    description: "Fix stale references in .story/ data",
    usage: "storybloq repair [--dry-run] [--canonicalize-refs]",
    flags: ["--dry-run", "--canonicalize-refs"],
  },
  {
    name: "config",
    description: "Manage project configuration (recipe overrides)",
    usage: "storybloq config <subcommand> [--format json|md]",
  },
  {
    name: "migrate",
    description: "Migrate config schema to the latest version",
    usage: "storybloq migrate [--dry-run] [--format json|md]",
    flags: ["--dry-run"],
  },
  {
    name: "feedback",
    description: "Community feedback via GitHub Issues",
    usage: "storybloq feedback list|create|vote [args] [--format json|md]",
  },
  {
    name: "dispatch",
    description: "Dispatch work to Agent View background sessions",
    usage: "storybloq dispatch [ids..] [--format json|md]",
  },
  {
    name: "node add",
    description: "Add a federation node to an orchestrator project",
    usage: "storybloq node add <name> --path <p> [--role <r>] [--kind <k>] [--format json|md]",
    flags: ["--path", "--role", "--kind"],
  },
  {
    name: "node update",
    description: "Update a federation node's metadata",
    usage: "storybloq node update <name> [--path <p>] [--role <r>] [--format json|md]",
    flags: ["--path", "--role"],
  },
  {
    name: "node remove",
    description: "Remove a federation node from an orchestrator project",
    usage: "storybloq node remove <name> [--format json|md]",
  },
];

export const MCP_TOOLS: readonly McpToolEntry[] = [
  { name: "storybloq_status", description: "Project summary: phase statuses, ticket/issue counts, blockers" },
  { name: "storybloq_phase_list", description: "All phases with derived status" },
  { name: "storybloq_phase_current", description: "First non-complete phase" },
  { name: "storybloq_phase_tickets", description: "Leaf tickets for a specific phase", params: ["phaseId"] },
  { name: "storybloq_ticket_list", description: "List leaf tickets with optional filters", params: ["status?", "phase?", "type?"] },
  { name: "storybloq_ticket_get", description: "Get a ticket by ID", params: ["id"] },
  { name: "storybloq_ticket_meta_get", description: "Get custom passthrough metadata from a ticket", params: ["id", "path?"] },
  { name: "storybloq_ticket_next", description: "Highest-priority unblocked ticket(s)", params: ["count?"] },
  { name: "storybloq_ticket_blocked", description: "All blocked tickets with dependencies" },
  { name: "storybloq_issue_list", description: "List issues with optional filters", params: ["status?", "severity?", "component?", "phase?"] },
  { name: "storybloq_issue_get", description: "Get an issue by ID", params: ["id"] },
  { name: "storybloq_issue_meta_get", description: "Get custom passthrough metadata from an issue", params: ["id", "path?"] },
  { name: "storybloq_handover_list", description: "List handover filenames (newest first)" },
  { name: "storybloq_handover_latest", description: "Content of most recent handover" },
  { name: "storybloq_handover_get", description: "Content of a specific handover", params: ["filename"] },
  { name: "storybloq_handover_create", description: "Create a handover from markdown content", params: ["content", "slug?"] },
  { name: "storybloq_blocker_list", description: "All roadmap blockers with status" },
  { name: "storybloq_validate", description: "Reference integrity + schema checks" },
  { name: "storybloq_recap", description: "Session diff — changes since last snapshot" },
  { name: "storybloq_recommend", description: "Context-aware ranked work suggestions", params: ["count?"] },
  { name: "storybloq_snapshot", description: "Save current project state snapshot" },
  { name: "storybloq_export", description: "Self-contained project document", params: ["phase?", "all?"] },
  { name: "storybloq_note_list", description: "List notes", params: ["status?", "tag?"] },
  { name: "storybloq_note_get", description: "Get note by ID", params: ["id"] },
  { name: "storybloq_note_create", description: "Create note", params: ["content", "title?", "tags?"] },
  { name: "storybloq_note_update", description: "Update note", params: ["id", "content?", "title?", "tags?", "status?"] },
  { name: "storybloq_ticket_create", description: "Create ticket", params: ["title", "type", "phase?", "description?", "blockedBy?", "parentTicket?"] },
  { name: "storybloq_ticket_update", description: "Update ticket", params: ["id", "status?", "title?", "type?", "order?", "description?", "phase?", "parentTicket?", "blockedBy?"] },
  { name: "storybloq_ticket_meta_set", description: "Set custom passthrough metadata on a ticket", params: ["id", "path", "value"] },
  { name: "storybloq_ticket_meta_unset", description: "Unset custom passthrough metadata from a ticket", params: ["id", "path"] },
  { name: "storybloq_issue_create", description: "Create issue", params: ["title", "severity", "impact", "components?", "relatedTickets?", "location?", "phase?"] },
  { name: "storybloq_issue_update", description: "Update issue", params: ["id", "status?", "title?", "severity?", "impact?", "resolution?", "components?", "relatedTickets?", "location?", "order?", "phase?"] },
  { name: "storybloq_issue_meta_set", description: "Set custom passthrough metadata on an issue", params: ["id", "path", "value"] },
  { name: "storybloq_issue_meta_unset", description: "Unset custom passthrough metadata from an issue", params: ["id", "path"] },
  { name: "storybloq_phase_create", description: "Create phase in roadmap", params: ["id", "name", "label", "description", "summary?", "after?", "atStart?"] },
  { name: "storybloq_lesson_list", description: "List lessons", params: ["status?", "tag?", "source?"] },
  { name: "storybloq_lesson_get", description: "Get lesson by ID", params: ["id"] },
  { name: "storybloq_lesson_digest", description: "Ranked digest of active lessons for context loading" },
  { name: "storybloq_lesson_create", description: "Create lesson", params: ["title", "content", "context", "source", "tags?", "supersedes?"] },
  { name: "storybloq_lesson_update", description: "Update lesson", params: ["id", "title?", "content?", "context?", "tags?", "status?", "supersedes?"] },
  { name: "storybloq_lesson_reinforce", description: "Reinforce lesson — increment count and update lastValidated", params: ["id"] },
  { name: "storybloq_selftest", description: "Integration smoke test — create/update/delete cycle" },
  { name: "storybloq_review_lenses_prepare", description: "Prepare multi-lens review on @storybloq/lenses: activation, secrets gate, context packaging, complete lens prompts", params: ["stage", "diff", "changedFiles", "ticketDescription?", "reviewRound?", "priorDeferrals?", "sessionId?"] },
  { name: "storybloq_review_lenses_synthesize", description: "Run the @storybloq/lenses merger pipeline programmatically over raw lens outputs; returns the ReviewVerdict envelope (no merger agent)", params: ["stage?", "lensResults", "activeLenses", "skippedLenses", "reviewRound?", "reviewId?", "diff?", "changedFiles?", "sessionId?"] },
  { name: "storybloq_review_lenses_judge", description: "Deterministic three-value verdict mapping over the synthesize ReviewVerdict plus convergence history (no judge agent)", params: ["reviewVerdict", "convergenceHistory?"] },
  { name: "storybloq_autonomous_guide", description: "Autonomous session orchestrator — call at every decision point to drive PICK_TICKET through COMPLETE", params: ["sessionId?", "action", "mode?", "ticketId?"] },
  { name: "storybloq_session_report", description: "Structured analysis of an autonomous session (works even if project state is corrupted)", params: ["sessionId"] },
  { name: "storybloq_register_subprocess", description: "Register a running subprocess so monitors can tell slow builds from hung agents", params: ["pid", "cmd", "category?", "sessionId?"] },
  { name: "storybloq_unregister_subprocess", description: "Unregister a subprocess after it completes (idempotent)", params: ["pid", "sessionId?"] },
  { name: "storybloq_node_list", description: "List configured federation nodes in an orchestrator project" },
  { name: "storybloq_node_init", description: "Initialize .story/ in a federation child node from the orchestrator", params: ["node", "type?", "language?"] },
  { name: "storybloq_node_add", description: "Add a federation node to an orchestrator project's config", params: ["name", "path", "role?", "kind?"] },
  { name: "storybloq_node_update", description: "Update a federation node's metadata (shallow-merge)", params: ["name", "path?", "role?"] },
];

export function handleReference(format: OutputFormat): string {
  return formatReference(COMMANDS, MCP_TOOLS, format);
}
