import { formatReference } from "../../core/output-formatter.js";
import type { CommandEntry, McpToolEntry } from "../../core/output-formatter.js";
import type { OutputFormat } from "../../models/types.js";

/**
 * User-facing CLI commands and full-project MCP tools. Hidden hook commands are excluded.
 * A drift-detection test verifies this stays in sync with actual registrations.
 */

export type { CommandEntry, McpToolEntry };

export const COMMANDS: readonly CommandEntry[] = [
  {
    name: "init",
    description: "Initialize a new .story/ project",
    usage: "storybloq init [--name <value>] [--force] [--type <value>] [--language <value>] [--node <value>] [--format <json|md>]",
    flags: ["--name", "--force", "--type", "--language", "--node", "--format"],
  },
  {
    name: "status",
    description:
      "Project summary: phase statuses, ticket/issue counts, blockers. --compact (T-320): JSON only, ignores --format. Reduces the payload: drops archivedNotes, deprecatedLessons, and issueFlow.semantics; reduces each session record (activeSessions/resumableSessions/expiredLeaseSessions) to sessionId, sourceDir, state, mode, ownerTask, leaseState, leaseExpiresAt, compactPending, dropping ticketId/ticketTitle; reduces bus to enabled, daemonState, deliveryMode, pendingMessages, unacknowledgedCritical, nextActions, dropping participants, wake, hookDelivery, deliveryCapabilities, and every other bus field. limitStops, sessionDiagnostics, arrangements/arrangementWarnings, and every other top-level field are kept whole.",
    usage: "storybloq status [--format <json|md>] [--client-task-id <value>] [--compact]",
    flags: ["--format", "--client-task-id", "--compact"],
  },
  {
    name: "ticket list",
    description: "List tickets with optional filters",
    usage: "storybloq ticket list [--status <value>] [--phase <value>] [--type <value>] [--format <json|md>] [--node <value>]",
    flags: ["--status", "--phase", "--type", "--format", "--node"],
  },
  {
    name: "ticket get",
    description: "Get ticket details by ID",
    usage: "storybloq ticket get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ticket next",
    description: "Suggest next ticket(s) to work on",
    usage: "storybloq ticket next [--format <json|md>] [--count <number>]",
    flags: ["--format", "--count"],
  },
  {
    name: "ticket blocked",
    description: "List blocked tickets with their blocking dependencies",
    usage: "storybloq ticket blocked [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ticket create",
    description: "Create a new ticket",
    usage: "storybloq ticket create --title <value> --type <value> [--phase <value>] [--description <value>] [--stdin] [--parent-ticket <value>] [--blocked-by <value>] [--cites-ruling <value>] [--format <json|md>] [--node <value>]",
    flags: ["--title", "--type", "--phase", "--description", "--stdin", "--parent-ticket", "--blocked-by", "--cites-ruling", "--format", "--node"],
  },
  {
    name: "ticket update",
    description: "Update a ticket",
    usage: "storybloq ticket update <id> [--status <value>] [--title <value>] [--type <value>] [--phase <value>] [--order <number>] [--description <value>] [--stdin] [--parent-ticket <value>] [--node <value>] [--force] [--clear-cites-rulings] [--blocked-by <value>] [--cross-node-blocked-by <value>] [--cites-ruling <value>] [--format <json|md>]",
    flags: ["--status", "--title", "--type", "--phase", "--order", "--description", "--stdin", "--parent-ticket", "--node", "--force", "--clear-cites-rulings", "--blocked-by", "--cross-node-blocked-by", "--cites-ruling", "--format"],
  },
  {
    name: "ticket meta",
    description: "Get, set, or unset custom passthrough metadata on a ticket",
    usage: "storybloq ticket meta <operation> <id> [path] [value] [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ticket delete",
    description: "Delete a ticket",
    usage: "storybloq ticket delete <id> [--force] [--hard] [--format <json|md>]",
    flags: ["--force", "--hard", "--format"],
  },
  {
    name: "issue list",
    description: "List issues with optional filters",
    usage: "storybloq issue list [--status <value>] [--severity <value>] [--component <value>] [--phase <value>] [--format <json|md>]",
    flags: ["--status", "--severity", "--component", "--phase", "--format"],
  },
  {
    name: "issue get",
    description: "Get issue details by ID",
    usage: "storybloq issue get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "issue create",
    description: "Create a new issue",
    usage: "storybloq issue create --title <value> --severity <value> [--impact <value>] [--stdin] [--phase <value>] [--dedupe-key <value>] [--created-by <value>] [--components <value>] [--related-tickets <value>] [--location <value>] [--source-ref <value>] [--cites-ruling <value>] [--format <json|md>]",
    flags: ["--title", "--severity", "--impact", "--stdin", "--phase", "--dedupe-key", "--created-by", "--components", "--related-tickets", "--location", "--source-ref", "--cites-ruling", "--format"],
  },
  {
    name: "issue update",
    description: "Update an issue",
    usage: "storybloq issue update <id> [--status <value>] [--title <value>] [--severity <value>] [--impact <value>] [--stdin] [--resolution <value>] [--order <number>] [--phase <value>] [--clear-cites-rulings] [--components <value>] [--related-tickets <value>] [--location <value>] [--source-ref <value>] [--cites-ruling <value>] [--format <json|md>]",
    flags: ["--status", "--title", "--severity", "--impact", "--stdin", "--resolution", "--order", "--phase", "--clear-cites-rulings", "--components", "--related-tickets", "--location", "--source-ref", "--cites-ruling", "--format"],
  },
  {
    name: "issue meta",
    description: "Get, set, or unset custom passthrough metadata on an issue",
    usage: "storybloq issue meta <operation> <id> [path] [value] [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "issue delete",
    description: "Delete an issue",
    usage: "storybloq issue delete <id> [--hard] [--format <json|md>]",
    flags: ["--hard", "--format"],
  },
  {
    name: "phase list",
    description: "List all phases with derived status",
    usage: "storybloq phase list [--format <json|md>] [--node <value>]",
    flags: ["--format", "--node"],
  },
  {
    name: "phase current",
    description: "Show current (first non-complete) phase",
    usage: "storybloq phase current [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "phase tickets",
    description: "List tickets in a specific phase",
    usage: "storybloq phase tickets --phase <value> [--format <json|md>]",
    flags: ["--phase", "--format"],
  },
  {
    name: "phase create",
    description: "Create a new phase",
    usage: "storybloq phase create --id <value> --name <value> --label <value> --description <value> [--summary <value>] [--after <value>] [--at-start] [--node <value>] [--format <json|md>]",
    flags: ["--id", "--name", "--label", "--description", "--summary", "--after", "--at-start", "--node", "--format"],
  },
  {
    name: "phase rename",
    description: "Rename/update phase metadata",
    usage: "storybloq phase rename <id> [--name <value>] [--label <value>] [--description <value>] [--summary <value>] [--format <json|md>]",
    flags: ["--name", "--label", "--description", "--summary", "--format"],
  },
  {
    name: "phase move",
    description: "Move a phase to a new position",
    usage: "storybloq phase move <id> [--after <value>] [--at-start] [--format <json|md>]",
    flags: ["--after", "--at-start", "--format"],
  },
  {
    name: "phase delete",
    description: "Delete a phase",
    usage: "storybloq phase delete <id> [--reassign <value>] [--format <json|md>]",
    flags: ["--reassign", "--format"],
  },
  {
    name: "handover list",
    description: "List handover filenames (newest first)",
    usage: "storybloq handover list [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "handover latest",
    description: "Content of most recent handover",
    usage: "storybloq handover latest [--count <number>] [--brief] [--priming] [--format <json|md>]",
    flags: ["--count", "--brief", "--priming", "--format"],
  },
  {
    name: "handover get",
    description: "Content of a specific handover",
    usage: "storybloq handover get <filename> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "handover create",
    description: "Create a new handover document",
    usage: "storybloq handover create [--content <value>] [--stdin] [--slug <value>] [--format <json|md>]",
    flags: ["--content", "--stdin", "--slug", "--format"],
  },
  {
    name: "handover template",
    description: "Scaffold a new handover document (category headings, Carried forward, marker)",
    usage: "storybloq handover template [--override <body>] [--format json|md]",
    flags: ["--override", "--format"],
  },
  {
    name: "blocker list",
    description: "List all roadmap blockers",
    usage: "storybloq blocker list [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "blocker add",
    description: "Add a new blocker",
    usage: "storybloq blocker add --name <value> [--note <value>] [--format <json|md>]",
    flags: ["--name", "--note", "--format"],
  },
  {
    name: "blocker clear",
    description: "Clear (resolve) a blocker",
    usage: "storybloq blocker clear --name <value> [--note <value>] [--format <json|md>]",
    flags: ["--name", "--note", "--format"],
  },
  {
    name: "note list",
    description: "List notes with optional status/tag filters",
    usage: "storybloq note list [--status <active|archived>] [--tag <value>] [--format <json|md>]",
    flags: ["--status", "--tag", "--format"],
  },
  {
    name: "note get",
    description: "Get a note by ID",
    usage: "storybloq note get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "note create",
    description: "Create a new note",
    usage: "storybloq note create [--content <value>] [--title <value>] [--stdin] [--tags <value>] [--format <json|md>]",
    flags: ["--content", "--title", "--stdin", "--tags", "--format"],
  },
  {
    name: "note update",
    description: "Update a note",
    usage: "storybloq note update <id> [--content <value>] [--title <value>] [--clear-tags] [--status <active|archived>] [--stdin] [--tags <value>] [--format <json|md>]",
    flags: ["--content", "--title", "--clear-tags", "--status", "--stdin", "--tags", "--format"],
  },
  {
    name: "note delete",
    description: "Delete a note",
    usage: "storybloq note delete <id> [--hard] [--format <json|md>]",
    flags: ["--hard", "--format"],
  },
  {
    name: "lesson list",
    description: "List lessons with optional status/tag/source filters",
    usage: "storybloq lesson list [--status <active|deprecated|superseded>] [--tag <value>] [--source <review|correction|postmortem|manual>] [--format <json|md>]",
    flags: ["--status", "--tag", "--source", "--format"],
  },
  {
    name: "lesson get",
    description: "Get a lesson by ID",
    usage: "storybloq lesson get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "lesson digest",
    description:
      "Ranked digest of active lessons. --limit/--select (T-320): one-line-per-lesson form; --select is phase:<id>/component:<name>/item:<id>, falls back to --limit.",
    usage: "storybloq lesson digest [--format json|md] [--limit <n>] [--select <selector,...>]",
    flags: ["--format", "--limit", "--select"],
  },
  {
    name: "lesson create",
    description: "Create a new lesson",
    usage: "storybloq lesson create --title <value> [--content <value>] --context <value> --source <review|correction|postmortem|manual> [--supersedes <value>] [--stdin] [--tags <value>] [--format <json|md>]",
    flags: ["--title", "--content", "--context", "--source", "--supersedes", "--stdin", "--tags", "--format"],
  },
  {
    name: "lesson update",
    description: "Update a lesson",
    usage: "storybloq lesson update <id> [--title <value>] [--content <value>] [--context <value>] [--clear-tags] [--status <active|deprecated|superseded>] [--stdin] [--tags <value>] [--format <json|md>]",
    flags: ["--title", "--content", "--context", "--clear-tags", "--status", "--stdin", "--tags", "--format"],
  },
  {
    name: "lesson reinforce",
    description: "Reinforce a lesson: increment count and update lastValidated",
    usage: "storybloq lesson reinforce <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    // Fork: storyknow knowledge packs.
    name: "lesson promote",
    description: "Promote a lesson into an attached storyknow knowledge pack (fork). The pack gains a K-entry (reinforcement count carried, origin stamped); the local lesson is superseded with a pointer.",
    usage: "storybloq lesson promote <id> --to <pack-name-or-path> [--force] [--format <json|md>]",
    flags: ["--to", "--force", "--format"],
  },
  {
    name: "lesson delete",
    description: "Delete a lesson",
    usage: "storybloq lesson delete <id> [--hard] [--format <json|md>]",
    flags: ["--hard", "--format"],
  },
  // Fork: storyknow knowledge packs. K-NNN entries live inside a knowledge pack
  // (a project created with `storybloq init --type knowledge`); consumers attach
  // packs via the `knowledge: ["<name-or-path>"]` config key (bare names resolve
  // under $STORYKNOW_HOME, default ~/dev/storyknow) and see attached entries in
  // `lesson digest` marked [<pack>]. One entry per subcommand so the generator's
  // positional/flag parse holds; the pack-vs-consumer split lives on `digest`.
  {
    name: "knowledge list",
    description: "List knowledge entries in this pack (fork)",
    usage: "storybloq knowledge list [--status <value>] [--tag <value>] [--source <value>] [--format <json|md>]",
    flags: ["--status", "--tag", "--source", "--format"],
  },
  {
    name: "knowledge get",
    description: "Get a knowledge entry by ID (fork)",
    usage: "storybloq knowledge get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "knowledge digest",
    description: "Ranked digest of knowledge (fork): inside a pack, the pack's own entries; inside a consumer project, all attached knowledge",
    usage: "storybloq knowledge digest [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "knowledge create",
    description: "Create a knowledge entry in this pack (fork)",
    usage: "storybloq knowledge create --title <value> --context <value> --source <value> [--content <value>] [--tags <value>] [--supersedes <id>] [--stdin] [--format <json|md>]",
    flags: ["--title", "--context", "--source", "--content", "--tags", "--supersedes", "--stdin", "--format"],
  },
  {
    name: "knowledge update",
    description: "Update a knowledge entry (fork)",
    usage: "storybloq knowledge update <id> [--title <value>] [--content <value>] [--context <value>] [--tags <value>] [--clear-tags] [--status <value>] [--stdin] [--format <json|md>]",
    flags: ["--title", "--content", "--context", "--tags", "--clear-tags", "--status", "--stdin", "--format"],
  },
  {
    name: "knowledge reinforce",
    description: "Reinforce a knowledge entry: increment count and update lastValidated (fork)",
    usage: "storybloq knowledge reinforce <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "knowledge delete",
    description: "Delete a knowledge entry (fork)",
    usage: "storybloq knowledge delete <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ruling list",
    description: "List owner-ruling attestation records",
    usage: "storybloq ruling list [--scope-tag <value>] [--superseded] [--format <json|md>]",
    flags: ["--scope-tag", "--superseded", "--format"],
  },
  {
    name: "ruling get",
    description: "Get a ruling by ID",
    usage: "storybloq ruling get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ruling create",
    description: "Record a ruling verbatim and cite it from the tickets or issues it binds",
    usage: "storybloq ruling create --text <value> --attribution <owner-direct|owner-via-manager-with-owner-veto|manager-delegated> --date <value> [--client-task-id <value>] [--scope-tag <value>] [--cites <value>] [--format <json|md>]",
    flags: ["--text", "--attribution", "--date", "--client-task-id", "--scope-tag", "--cites", "--format"],
  },
  {
    name: "ruling supersede",
    description: "Supersede a ruling: link an existing one with --with, or record a new superseding ruling",
    usage: "storybloq ruling supersede <id> [--with <value>] [--text <value>] [--attribution <owner-direct|owner-via-manager-with-owner-veto|manager-delegated>] [--date <value>] [--client-task-id <value>] [--scope-tag <value>] [--format <json|md>]",
    flags: ["--with", "--text", "--attribution", "--date", "--client-task-id", "--scope-tag", "--format"],
  },
  {
    name: "arrangement compact",
    description: "Compact a duet arrangement's coordination checkpoint: resolved assignments keep their last event, overflow moves to an archive list. Pen only",
    usage: "storybloq arrangement compact <id> [--client-task-id <id>] [--format json|md]",
    flags: ["--client-task-id", "--format"],
  },
  {
    name: "arrangement rotate",
    description: "Close a duet arrangement at capacity and carry its open assignments, verified session and earmarks into a fresh successor. Pen only",
    usage: "storybloq arrangement rotate <id> [--client-task-id <id>] [--format json|md]",
    flags: ["--client-task-id", "--format"],
  },
  {
    name: "validate",
    description: "Reference, schema, source-provenance, and loader-independent JSON checks",
    usage: "storybloq validate [--integrity-only] [--format <json|md>]",
    flags: ["--integrity-only", "--format"],
  },
  {
    name: "snapshot",
    description: "Save current project state for session diffs",
    usage: "storybloq snapshot [--quiet] [--format <json|md>]",
    flags: ["--quiet", "--format"],
  },
  {
    name: "recap",
    description: "Session diff: changes since last snapshot + suggested actions",
    usage: "storybloq recap [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "export",
    description: "Self-contained project document for sharing",
    usage: "storybloq export [--phase <value>] [--all] [--format <json|md>]",
    flags: ["--phase", "--all", "--format"],
  },
  {
    name: "recommend",
    description: "Context-aware work suggestions",
    usage: "storybloq recommend [--format <json|md>] [--count <number>] [--with-actionability]",
    flags: ["--format", "--count", "--with-actionability"],
  },
  {
    name: "reference",
    description: "Print CLI command and MCP tool reference",
    usage: "storybloq reference [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "selftest",
    description: "Run integration smoke test: create/update/delete cycle across all entity types",
    usage: "storybloq selftest [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "health",
    description: "Check the tooling around this project: auto-compact window, CLI version, Codex review bridge (launched and answered, not just registered), /story skill, cross-session messaging, duplicate hook rows. --format json is the shared {version, data} envelope with the result under data; --raw unwraps it",
    usage: "storybloq health [--only <ids>] [--refresh] [--format json|md] [--raw]",
    flags: ["--only", "--refresh", "--format"],
  },
  {
    name: "codex-review",
    description: "Run native Codex plan or code review for an autonomous session",
    usage: "storybloq codex-review <kind> --session <value> [--format <guide-report>]",
    flags: ["--session", "--format"],
  },
  {
    name: "limit-status",
    description: "Show pending usage-limit auto-resumes (global across projects); cancel or requeue records",
    usage: "storybloq limit-status [--cancel <value>] [--requeue <value>] [--recent] [--format <json|md>]",
    flags: ["--cancel", "--requeue", "--recent", "--format"],
  },
  {
    name: "session intel-start",
    description: "Capture the auto-compact setting for the current process era (SessionStart hook)",
    usage: "storybloq session intel-start [--client <claude|codex>]",
    flags: ["--client"],
  },
  {
    name: "session intel-prompt",
    description: "Sample context pressure and emit additionalContext at imperative pressure (UserPromptSubmit hook)",
    usage: "storybloq session intel-prompt [--client <claude|codex>]",
    flags: ["--client"],
  },
  {
    name: "session intel",
    description: "Context usage, expected auto-compaction point with provenance, pressure state (ok/advisory/imperative/compact-needed), session facts. Works without .story/. --transcript must be ~/.claude/projects/<project>/<sessionId>.jsonl (a regular file, not a symlink); a refusal names the rule that failed",
    usage: "storybloq session intel [--session-id <id>] [--transcript <path>] [--caller-model <model>] [--full] [--client-task-id <id>] [--format json|md]",
    flags: ["--session-id", "--transcript", "--caller-model", "--full", "--client-task-id", "--format"],
  },
  {
    name: "setup",
    description: "Install Storybloq skill, MCP, and hooks for Claude, Codex, or both",
    usage: "storybloq setup [--client <claude|codex|all>] [--skip-hooks] [--skip-skill]",
    flags: ["--client", "--skip-hooks", "--skip-skill"],
  },
  {
    name: "setup-skill",
    description: "Compatibility alias for `storybloq setup --client claude`",
    usage: "storybloq setup-skill [--skip-hooks]",
    flags: ["--skip-hooks"],
  },
  {
    name: "update",
    description: "Install the newest storybloq into the running Node's prefix, re-run setup for your AI clients, and say when to restart (on Windows it prints the two manual steps instead)",
    usage: "storybloq update [--client <claude|codex|all>]",
    flags: ["--client"],
  },
  {
    name: "reconcile",
    description: "Detect and fix duplicate displayIds across all entity types",
    usage: "storybloq reconcile [--dry-run] [--ci] [--rebalance-ranks] [--format <json|md>]",
    flags: ["--dry-run", "--ci", "--rebalance-ranks", "--format"],
  },
  {
    name: "conflicts list",
    description: "List all items with unresolved merge conflicts",
    usage: "storybloq conflicts list [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "conflicts show",
    description: "Show field-level conflict detail for an item",
    usage: "storybloq conflicts show <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "resolve",
    description: "Resolve merge conflicts on a .story/ item",
    usage: "storybloq resolve <id> [--field <value>] [--use <ours|theirs>] [--value <value>] [--format <json|md>]",
    flags: ["--field", "--use", "--value", "--format"],
  },
  {
    name: "merge-driver",
    description: "Git merge driver for .story/ JSON files (registered via team setup)",
    usage: "storybloq merge-driver <ancestor> <ours> <theirs> <pathname>",
    flags: [],
  },
  {
    name: "team init",
    description: "Enable team mode on this project",
    usage: "storybloq team init [--claim-staleness-hours <number>] [--id-allocator <local|git-refs>] [--format <json|md>]",
    flags: ["--claim-staleness-hours", "--id-allocator", "--format"],
  },
  {
    name: "team setup",
    description: "Install the git merge driver and .gitattributes for team mode",
    usage: "storybloq team setup [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "team doctor",
    description: "Run team health checks on the project",
    usage: "storybloq team doctor [--ci] [--format <json|md>]",
    flags: ["--ci", "--format"],
  },
  {
    name: "team reserve",
    description: "Reserve display IDs via remote git refs",
    usage: "storybloq team reserve <type> [--count <number>] [--format <json|md>]",
    flags: ["--count", "--format"],
  },
  {
    name: "gc",
    description: "Remove tombstoned files past retention period",
    usage: "storybloq gc [--apply] [--force] [--retention-days <number>] [--format <json|md>]",
    flags: ["--apply", "--force", "--retention-days", "--format"],
  },
  {
    name: "repair",
    description: "Fix stale references in .story/ data",
    usage: "storybloq repair [--dry-run] [--canonicalize-refs]",
    flags: ["--dry-run", "--canonicalize-refs"],
  },
  {
    name: "migrate",
    description: "Migrate config schema to the latest version",
    usage: "storybloq migrate [--dry-run] [--format <json|md>]",
    flags: ["--dry-run", "--format"],
  },
  {
    name: "dispatch",
    description: "Dispatch work to Agent View background sessions",
    usage: "storybloq dispatch [ids..] [--format <json|md>] [--recommend] [--all] [--count <number>] [--yes] [--dry-run]",
    flags: ["--format", "--recommend", "--all", "--count", "--yes", "--dry-run"],
  },
  {
    name: "bus init",
    description: "Low-level initializer: enable the local Storybloq Bus v2 for this project (prefer `storybloq bus setup`). Initializes a fresh v2 runtime only; if a v1 runtime is present it refuses with `upgrade_required` and directs you to `storybloq bus setup`, which resolves this task's identity and runs the guided drain/upgrade.",
    usage: "storybloq bus init [--format <md|json>]",
    flags: ["--format"],
  },
  {
    name: "bus setup",
    description: "Connect this task to the Storybloq Bus in one idempotent, resumable command. Initializes or upgrades the runtime, joins this task's endpoint, and (when hook delivery is enabled) enables this client's guarded on-boundary hooks. With one endpoint it ends with a handoff line inviting the other task to connect. --replace <endpoint-id> retires a proven-offline incumbent and takes its place, redelivering that endpoint's undelivered mail to this successor. --force-archive overrides unread noncritical v1 delivery only during a v1->v2 upgrade; it never bypasses ship-gate blockers (unacknowledged critical messages, parked unresolved critical threads, quarantined threads).",
    usage: "storybloq bus setup [--client <claude|codex>] [--task-id <value>] [--surface <claude_cli|codex_cli|codex_desktop>] [--delivery <live|poll>] [--wake <never|idle>] [--session-name <value>] [--transport-address <value>] [--replace <value>] [--force-archive] [--format <md|json>]",
    flags: ["--client", "--task-id", "--surface", "--delivery", "--wake", "--session-name", "--transport-address", "--replace", "--force-archive", "--format"],
  },
  {
    name: "bus auto-attach",
    description: "Turn per-session Bus auto-attach on or off for this project (opt-in, default off). `on` runs the full `bus setup` bootstrap once (initializing the runtime, joining this task, and installing the global client hooks) and sets the opt-in flag; thereafter every new session auto-attaches at SessionStart with its on-boundary delivery tiers enabled, no command, and a session that finds a proven-dead peer reclaims its slot and inherits its undelivered mail. `off` clears the flag and leaves the runtime and existing endpoints in place.",
    usage: "storybloq bus auto-attach <state> [--client <claude|codex>] [--task-id <value>] [--surface <claude_cli|codex_cli|codex_desktop>] [--force-archive] [--format <md|json>]",
    flags: ["--client", "--task-id", "--surface", "--force-archive", "--format"],
  },
  {
    name: "bus join",
    description: "Deprecated: roles are now per-message, so the legacy role argument is ignored. Use `storybloq bus setup`.",
    usage: "storybloq bus join [legacy-role] [--client <claude|codex>] [--task-id <value>] [--surface <claude_cli|codex_cli|codex_desktop>] [--replace <value>] [--format <md|json>]",
    flags: ["--client", "--task-id", "--surface", "--replace", "--format"],
  },
  {
    name: "bus leave",
    description: "Retire the Bus endpoint owned by this task",
    usage: "storybloq bus leave [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--format"],
  },
  {
    name: "bus endpoint retire",
    description: "Force-retire an endpoint with unknown liveness",
    usage: "storybloq bus endpoint retire <endpoint-id> --force --reason <value> [--format <md|json>]",
    flags: ["--force", "--reason", "--format"],
  },
  {
    name: "bus send",
    description: "Create a Bus thread or send a reply. Routing always targets the sole peer; `--to` is deprecated and ignored.",
    usage: "storybloq bus send [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] [--thread <value>] [--thread-kind <issue_notice|question|coordination|patch_request>] [--predecessor-thread <value>] [--to <implementer|reviewer>] --kind <issue_notice|question|reply|status|patch_request|claim|release> [--severity <critical|high|medium|low|info>] --body <value> --idempotency-key <value> [--in-reply-to <value>] [--issue <value>] [--ticket <value>] [--commit <value>] [--ci-run <value>] [--file <value>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--thread", "--thread-kind", "--predecessor-thread", "--to", "--kind", "--severity", "--body", "--idempotency-key", "--in-reply-to", "--issue", "--ticket", "--commit", "--ci-run", "--file", "--format"],
  },
  {
    name: "bus poll",
    description: "Poll unacknowledged messages for the task-bound endpoint. --limit bounds how many messages are returned (applies to the wait drain too). With --wait, block until a message arrives or --timeout elapses (v2 only), then exit: 0 = message delivered, 4 = timed out, 5 = another --wait already owns this endpoint.",
    usage: "storybloq bus poll [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] [--limit <number>] [--wait] [--timeout <number>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--limit", "--wait", "--timeout", "--format"],
  },
  {
    name: "bus ack",
    description: "Record delivery disposition for one Bus message",
    usage: "storybloq bus ack <message-id> [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] --disposition <accepted|rejected|deferred> [--reason <value>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--disposition", "--reason", "--format"],
  },
  {
    name: "bus status",
    description: "Show concise Bus runtime state",
    usage: "storybloq bus status [--format <md|json>]",
    flags: ["--format"],
  },
  {
    name: "bus doctor",
    description: "Validate Bus storage, endpoint, and mailbox integrity",
    usage: "storybloq bus doctor [--format <md|json>]",
    flags: ["--format"],
  },
  {
    name: "bus check",
    description: "Run the critical Bus release gate",
    usage: "storybloq bus check --ship [--format <md|json>]",
    flags: ["--ship", "--format"],
  },
  {
    name: "bus export",
    description: "Explicitly export one Bus transcript",
    usage: "storybloq bus export <thread-id> [--format <md|json>]",
    flags: ["--format"],
  },
  {
    name: "node add",
    description: "Add a federation node to an orchestrator project",
    usage: "storybloq node add <name> --path <value> [--stack <value>] [--role <value>] [--kind <value>] [--summary <value>] [--depends-on <value>] [--link <value>] [--format <json|md>]",
    flags: ["--path", "--stack", "--role", "--kind", "--summary", "--depends-on", "--link", "--format"],
  },
  {
    name: "node link",
    description: "Record which orchestrator this project belongs to (run from the node)",
    usage: "storybloq node link [orchestrator] [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "node update",
    description: "Update a federation node's metadata",
    usage: "storybloq node update <name> [--path <value>] [--stack <value>] [--role <value>] [--kind <value>] [--summary <value>] [--clear-depends-on] [--clear-links] [--depends-on <value>] [--link <value>] [--format <json|md>]",
    flags: ["--path", "--stack", "--role", "--kind", "--summary", "--clear-depends-on", "--clear-links", "--depends-on", "--link", "--format"],
  },
  {
    name: "node remove",
    description: "Remove a federation node from an orchestrator project",
    usage: "storybloq node remove <name> [--force] [--prune] [--format <json|md>]",
    flags: ["--force", "--prune", "--format"],
  },
  {
    name: "arrangement coordinate",
    description: "Record a pen-owned duet coordination operation",
    usage: "storybloq arrangement coordinate <id> --json <value> [--client-task-id <value>] [--format <json|md>]",
    flags: ["--json", "--client-task-id", "--format"],
  },
  {
    name: "arrangement list",
    description: "List arrangements",
    usage: "storybloq arrangement list [--lifecycle <active|suspended|closed>] [--format <json|md>]",
    flags: ["--lifecycle", "--format"],
  },
  {
    name: "arrangement get",
    description: "Get an arrangement",
    usage: "storybloq arrangement get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "arrangement create",
    description: "Create a new arrangement",
    usage: "storybloq arrangement create --unreachability-irreversible <hold|escalate> [--unreachability-reversible <hold|escalate|proceed>] [--bounds <value>] [--party <value>] [--format <json|md>]",
    flags: ["--unreachability-irreversible", "--unreachability-reversible", "--bounds", "--party", "--format"],
  },
  {
    name: "arrangement update",
    description: "Update an arrangement",
    usage: "storybloq arrangement update <id> [--lifecycle <active|suspended|closed>] [--format <json|md>]",
    flags: ["--lifecycle", "--format"],
  },
  {
    name: "bus endpoint list",
    description: "List endpoints with their wake configuration and last wake outcome",
    usage: "storybloq bus endpoint list [--format <md|json>]",
    flags: ["--format"],
  },
  {
    name: "bus hooks enable",
    description: "Opt this project into guarded SessionStart and Stop delivery",
    usage: "storybloq bus hooks enable [--client <claude|codex|all>] [--format <md|json>]",
    flags: ["--client", "--format"],
  },
  {
    name: "bus hooks disable",
    description: "Disable guarded Bus hook delivery for this project",
    usage: "storybloq bus hooks disable [--client <claude|codex|all>] [--format <md|json>]",
    flags: ["--client", "--format"],
  },
  {
    name: "bus redeliver",
    description: "Redeliver a hop-cap-parked, never-dropped Bus message onto a fresh successor thread",
    usage: "storybloq bus redeliver [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] --predecessor-thread <value> --refused-entry-hash <value> [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--predecessor-thread", "--refused-entry-hash", "--format"],
  },
  {
    name: "bus thread show",
    description: "Show an integrity-verified participant thread",
    usage: "storybloq bus thread show <thread-id> [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--format"],
  },
  {
    name: "bus thread update",
    description: "Park, resolve, or reopen a participant thread",
    usage: "storybloq bus thread update <thread-id> [--endpoint <value>] [--client <claude|codex>] [--task-id <value>] --action <park|resolve|reopen> [--reason <value>] [--resolution <value>] [--commit <value>] [--ci-run <value>] [--format <md|json>]",
    flags: ["--endpoint", "--client", "--task-id", "--action", "--reason", "--resolution", "--commit", "--ci-run", "--format"],
  },
  {
    name: "config set-overrides",
    description: "Set or clear recipe overrides in config.json",
    usage: "storybloq config set-overrides [--json <value>] [--clear] [--deep] [--format <json|md>]",
    flags: ["--json", "--clear", "--deep", "--format"],
  },
  {
    name: "config set-federation",
    description: "Set federation settings (orchestrator only)",
    usage: "storybloq config set-federation [--allow-node-writes] [--format <json|md>]",
    flags: ["--allow-node-writes", "--format"],
  },
  {
    name: "earmark get",
    description: "Get the earmark on a ticket or issue",
    usage: "storybloq earmark get <ref> [--format <json|md>] [--node <value>]",
    flags: ["--format", "--node"],
  },
  {
    name: "earmark reserve",
    description: "Reserve a ticket or issue for a role, pending pickup",
    usage: "storybloq earmark reserve <ref> --role <pen|worker> [--arrangement <value>] [--format <json|md>] [--node <value>]",
    flags: ["--role", "--arrangement", "--format", "--node"],
  },
  {
    name: "earmark assign",
    description: "Assign a ticket or issue's earmark directly to a live session (direct placement, or an explicit reserved -> assigned conversion)",
    usage: "storybloq earmark assign <ref> --to <value> --role <pen|worker> [--arrangement <value>] [--format <json|md>] [--node <value>]",
    flags: ["--to", "--role", "--arrangement", "--format", "--node"],
  },
  {
    name: "earmark release",
    description: "Release (clear) a ticket or issue's earmark",
    usage: "storybloq earmark release <ref> [--arrangement <value>] [--format <json|md>] [--node <value>]",
    flags: ["--arrangement", "--format", "--node"],
  },
  {
    name: "feedback list",
    description: "List community feedback",
    usage: "storybloq feedback list [--category <bug|feature|idea>] [--format <json|md>]",
    flags: ["--category", "--format"],
  },
  {
    name: "feedback create",
    description: "Create new feedback (opens browser)",
    usage: "storybloq feedback create --title <value> [--category <bug|feature|idea>] [--body <value>]",
    flags: ["--title", "--category", "--body"],
  },
  {
    name: "feedback vote",
    description: "Vote on feedback (opens browser)",
    usage: "storybloq feedback vote <number>",
    flags: [],
  },
  {
    name: "gate-ack list",
    description: "List gate-acks",
    usage: "storybloq gate-ack list [--arrangement <value>] [--ticket <value>] [--format <json|md>]",
    flags: ["--arrangement", "--ticket", "--format"],
  },
  {
    name: "gate-ack get",
    description: "Get a gate-ack",
    usage: "storybloq gate-ack get <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "gate-ack create",
    description: "Create a gate-ack",
    usage: "storybloq gate-ack create --arrangement <value> --gate <value> --ticket <value> [--plan-file <value>] [--from-staged] [--codex-session-id <value>] [--verdict <value>] [--rounds <number>] [--deltas <value>] [--format <json|md>]",
    flags: ["--arrangement", "--gate", "--ticket", "--plan-file", "--from-staged", "--codex-session-id", "--verdict", "--rounds", "--deltas", "--format"],
  },
  {
    name: "gate-ack contest",
    description: "Mark a gate-ack contested (record + surfaced flag only)",
    usage: "storybloq gate-ack contest <id> --reason <value> [--format <json|md>]",
    flags: ["--reason", "--format"],
  },
  {
    name: "landings",
    description: "Commits that touched tickets/issues, with review coverage (CLI-only; no MCP tool)",
    usage: "storybloq landings [--since <value>] [--limit <number>] [--format <json|md>]",
    flags: ["--since", "--limit", "--format"],
  },
  {
    name: "node list",
    description: "List configured nodes",
    usage: "storybloq node list [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "review-stats",
    description: "Review efficiency metrics over review verdict artifacts",
    usage: "storybloq review-stats [--fleet <value>] [--open-window] [--close-window] [--contract] [--format <json|md>]",
    flags: ["--fleet", "--open-window", "--close-window", "--contract", "--format"],
  },
  {
    name: "session compact-prepare",
    description: "Prepare session for compaction (PreCompact hook)",
    usage: "storybloq session compact-prepare [--client <claude|codex>]",
    flags: ["--client"],
  },
  {
    name: "session resume-prompt",
    description: "Output resume instruction after compaction (SessionStart hook)",
    usage: "storybloq session resume-prompt [--codex-hook-json]",
    flags: ["--codex-hook-json"],
  },
  {
    name: "session limit-stop",
    description: "Record a usage-limit stop for auto-resume (StopFailure hook)",
    usage: "storybloq session limit-stop",
    flags: [],
  },
  {
    name: "session clear-compact",
    description: "Clear stale compact marker (admin)",
    usage: "storybloq session clear-compact [sessionId] [--force]",
    flags: ["--force"],
  },
  {
    name: "session stop",
    description: "Stop an active session (admin)",
    usage: "storybloq session stop [sessionId]",
    flags: [],
  },
  {
    name: "session list",
    description: "List sessions on disk (admin)",
    usage: "storybloq session list [--status <active|completed|superseded|all>] [--format <text|json>]",
    flags: ["--status", "--format"],
  },
  {
    name: "session show",
    description: "Show details of a session (admin)",
    usage: "storybloq session show <sessionId> [--format <text|json>] [--events <number>]",
    flags: ["--format", "--events"],
  },
  {
    name: "session repair",
    description: "Supersede orphaned sessions (admin)",
    usage: "storybloq session repair [sessionId] [--dry-run] [--all] [--yes]",
    flags: ["--dry-run", "--all", "--yes"],
  },
  {
    name: "session delete",
    description: "Delete a session directory (admin, destructive)",
    usage: "storybloq session delete <sessionId> [--yes]",
    flags: ["--yes"],
  },
  {
    name: "session health",
    description: "Derive and display session health state",
    usage: "storybloq session health [sessionId]",
    flags: [],
  },
  {
    name: "session watch",
    description: "Stream session health state changes",
    usage: "storybloq session watch [sessionId] [--events] [--quiet]",
    flags: ["--events", "--quiet"],
  },
  {
    name: "session milestone",
    description: "Report a self-described work milestone for presence display (duet/arrangement sessions)",
    usage: "storybloq session milestone <kind> [--gate-name <value>] [--note <value>] [--client-task-id <value>] [--format <text|json>]",
    flags: ["--gate-name", "--note", "--client-task-id", "--format"],
  },
  {
    name: "roster start",
    description: "Start (or restart) a seat on the roster: a session or one of its subagents. JSON envelope; no_project outside a ledger",
    usage: "storybloq roster start [--stdin] [--client-task-id <value>] [--agent-id <value>] [--session-id <value>] [--description <value>] [--format <json>]",
    flags: ["--stdin", "--client-task-id", "--agent-id", "--session-id", "--description", "--format"],
  },
  {
    name: "roster heartbeat",
    description: "Refresh a running seat's lastSeenAt; --generation from the start result is required",
    usage: "storybloq roster heartbeat --generation <number> [--stdin] [--client-task-id <value>] [--agent-id <value>] [--format <json>]",
    flags: ["--stdin", "--client-task-id", "--agent-id", "--generation", "--format"],
  },
  {
    name: "roster end",
    description: "End a seat with a terminal state (completed/failed/killed/detached); --generation required",
    usage: "storybloq roster end --generation <number> --state <value> [--stdin] [--client-task-id <value>] [--agent-id <value>] [--format <json>]",
    flags: ["--stdin", "--client-task-id", "--agent-id", "--generation", "--state", "--format"],
  },
  {
    name: "roster list",
    description: "List seats (Bus endpoints merged): running by default, every seat including terminal ones with --all",
    usage: "storybloq roster list [--all] [--format <json|md>]",
    flags: ["--all", "--format"],
  },
  {
    name: "team config show",
    description: "Show current team configuration",
    usage: "storybloq team config show [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "team config set",
    description: "Set a team configuration value",
    usage: "storybloq team config set <key> <value> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ticket move",
    description: "Move a ticket relative to another (fractional rank)",
    usage: "storybloq ticket move <id> [--after <value>] [--before <value>] [--format <json|md>]",
    flags: ["--after", "--before", "--format"],
  },
  {
    name: "ticket unclaim",
    description: "Remove claim from a ticket",
    usage: "storybloq ticket unclaim <id> [--format <json|md>]",
    flags: ["--format"],
  },
  {
    name: "ticket start",
    description: "Claim a ticket and set status to inprogress",
    usage: "storybloq ticket start <id> [--force] [--format <json|md>]",
    flags: ["--force", "--format"],
  },
];

export const MCP_TOOLS: readonly McpToolEntry[] = [
  { name: "storybloq_status", description: "Project summary; markdown default, JSON includes session ownership/leases. clientTaskId enriches this session's arrangementPresence/ownerIdentity; omit to inherit environment identity. compact always returns reduced JSON: see CLI status for retained/dropped fields.", params: ["format?","clientTaskId?","compact?"] },
  { name: "storybloq_roster_get", description: "Seat roster: live sessions and subagents (Bus endpoints merged) with live/stale/terminal counts; terminal seats hidden unless all. Read-only; writes are CLI-only.", params: ["format?","all?"] },
  { name: "storybloq_phase_list", description: "All phases with derived status", params: [] },
  { name: "storybloq_phase_current", description: "First non-complete phase", params: [] },
  { name: "storybloq_phase_tickets", description: "Leaf tickets for a specific phase", params: ["phaseId","node?"] },
  { name: "storybloq_ticket_list", description: "List leaf tickets with optional filters", params: ["status?","phase?","type?","node?"] },
  { name: "storybloq_ticket_get", description: "Get a ticket by ID", params: ["id","format?","withActionability?","node?"] },
  { name: "storybloq_ticket_meta_get", description: "Get custom passthrough metadata from a ticket", params: ["id","path?"] },
  { name: "storybloq_ticket_next", description: "Highest-priority unblocked ticket(s)", params: ["count?","node?"] },
  { name: "storybloq_ticket_blocked", description: "All blocked tickets with dependencies", params: ["node?"] },
  { name: "storybloq_issue_list", description: "List issues with optional filters", params: ["status?","severity?","component?","phase?","node?"] },
  { name: "storybloq_issue_get", description: "Get an issue by ID", params: ["id","format?","withActionability?","node?"] },
  { name: "storybloq_issue_meta_get", description: "Get custom passthrough metadata from an issue", params: ["id","path?"] },
  { name: "storybloq_handover_list", description: "List handover filenames (newest first)", params: [] },
  { name: "storybloq_handover_latest", description: "Content of most recent handover", params: ["count?","brief?","priming?","format?"] },
  { name: "storybloq_handover_get", description: "Content of a specific handover", params: ["filename","format?"] },
  { name: "storybloq_handover_create", description: "Create a handover from markdown content", params: ["content","slug?"] },
  { name: "storybloq_blocker_list", description: "All roadmap blockers with status", params: [] },
  { name: "storybloq_validate", description: "Reference, schema, source-provenance, and loader-independent JSON checks", params: ["format?","integrityOnly?"] },
  { name: "storybloq_recap", description: "Session diff: changes since last snapshot", params: [] },
  { name: "storybloq_recommend", description: "Context-aware ranked work suggestions", params: ["count?","node?"] },
  { name: "storybloq_snapshot", description: "Save current project state snapshot", params: [] },
  { name: "storybloq_export", description: "Self-contained project document", params: ["phase?","all?"] },
  { name: "storybloq_note_list", description: "List notes", params: ["status?","tag?"] },
  { name: "storybloq_note_get", description: "Get note by ID", params: ["id"] },
  { name: "storybloq_note_create", description: "Create note", params: ["content","title?","tags?"] },
  { name: "storybloq_note_update", description: "Update note", params: ["id","content?","title?","tags?","status?"] },
  { name: "storybloq_ticket_create", description: "Create ticket", params: ["title","type","phase?","description?","blockedBy?","parentTicket?","citesRuling?","node?"] },
  { name: "storybloq_ticket_update", description: "Update ticket", params: ["id","status?","title?","type?","order?","description?","phase?","parentTicket?","blockedBy?","crossNodeBlockedBy?","force?","citesRuling?","clearCitesRulings?","node?"] },
  { name: "storybloq_ticket_meta_set", description: "Set custom passthrough metadata on a ticket", params: ["id","path","value?"] },
  { name: "storybloq_ticket_meta_unset", description: "Unset custom passthrough metadata from a ticket", params: ["id","path"] },
  { name: "storybloq_issue_create", description: "Create issue with optional durable review provenance and retry deduplication", params: ["title","severity","impact","components?","relatedTickets?","location?","sourceRefs?","dedupeKey?","createdBy?","phase?","citesRuling?","node?"] },
  { name: "storybloq_issue_update", description: "Update issue", params: ["id","status?","title?","severity?","impact?","resolution?","components?","relatedTickets?","location?","sourceRefs?","order?","phase?","citesRuling?","clearCitesRulings?","node?"] },
  { name: "storybloq_issue_meta_set", description: "Set custom passthrough metadata on an issue", params: ["id","path","value?"] },
  { name: "storybloq_issue_meta_unset", description: "Unset custom passthrough metadata from an issue", params: ["id","path"] },
  { name: "storybloq_phase_create", description: "Create phase in roadmap", params: ["id","name","label","description","summary?","after?","atStart?"] },
  { name: "storybloq_lesson_list", description: "List lessons", params: ["status?","tag?","source?"] },
  { name: "storybloq_lesson_get", description: "Get lesson by ID", params: ["id"] },
  { name: "storybloq_lesson_digest", description: "Ranked digest of active lessons. limit/select (T-320); see CLI lesson digest.", params: ["limit?","select?"] },
  { name: "storybloq_lesson_create", description: "Create lesson", params: ["title","content","context","source","tags?","supersedes?"] },
  { name: "storybloq_lesson_update", description: "Update lesson", params: ["id","title?","content?","context?","tags?","status?"] },
  { name: "storybloq_lesson_reinforce", description: "Reinforce lesson: increment count and update lastValidated", params: ["id"] },
  { name: "storybloq_ruling_list", description: "List rulings, optionally filtered by scope tag or superseded state", params: ["scopeTag?","superseded?"] },
  { name: "storybloq_ruling_get", description: "Get a ruling by ID", params: ["id"] },
  { name: "storybloq_ruling_create", description: "Record a ruling verbatim; cites adds its id to each named ticket or issue in the same transaction", params: ["text","attribution","date","scopeTags?","cites?","clientTaskId?"] },
  { name: "storybloq_ruling_supersede", description: "Supersede a ruling: link an existing one with `with`, or record a new superseding ruling", params: ["id","with?","text?","attribution?","date?","scopeTags?","clientTaskId?"] },
  { name: "storybloq_selftest", description: "Integration smoke test: create/update/delete cycle", params: [] },
  { name: "storybloq_health", description: "Tooling check: auto-compact window, CLI version, Codex review bridge (launched and answered, not just registered), /story skill, cross-session message delivery. Works without .story/, read-only", params: ["format?","only?","refresh?"] },
  { name: "storybloq_review_lenses_prepare", description: "Prepare multi-lens review on @storybloq/lenses: activation, secrets gate, context packaging, cited-ruling delivery, complete lens prompts", params: ["stage","diff","changedFiles","ticketDescription?","reviewRound?","priorDeferrals?","sessionId?","target?"] },
  { name: "storybloq_review_lenses_synthesize", description: "Run the @storybloq/lenses merger pipeline programmatically over raw lens outputs; returns the ReviewVerdict envelope (no merger agent). Echo prepare's citedRulingsUndelivered here; without a sessionId it is the only route a delivery hold has", params: ["stage?","lensResults","activeLenses","skippedLenses","reviewRound?","reviewId?","diff?","changedFiles?","sessionId?","citedRulingsUndelivered?"] },
  { name: "storybloq_review_lenses_judge", description: "Deterministic three-value verdict mapping over the synthesize ReviewVerdict plus convergence history (no judge agent). Returns capReasons, coverageOnlyCap and uncoveredCoreLenses; report capReasons with the round or a coverage cap is routed like a findings cap", params: ["reviewVerdict?","convergenceHistory?"] },
  { name: "storybloq_autonomous_guide", description: "Autonomous session orchestrator -- call at every decision point to drive PICK_TICKET through COMPLETE", params: ["sessionId","action","clientTaskId?","takeover?","ownerGoneCandidateTakeover?","ownerGoneCandidateCancel?","mode?","reviewEffort?","ticketId?","targetWork?","report?"] },
  { name: "storybloq_session_guard", description: "Session ownership verdict: is anything running, and may I write? Reads only .story/sessions/, no ledger load. Also registered in degraded mode", params: ["clientTaskId?"] },
  { name: "storybloq_session_milestone", description: "Self-reported implementing/gate-hold/blocked-external/reviewing milestone on this session's presence, never a computed verdict. gate-hold requires gateName. Lock contention or write failure returns a retryable error.", params: ["kind","gateName?","note?","clientTaskId?"] },
  { name: "storybloq_session_report", description: "Structured analysis of an autonomous session (works even if project state is corrupted)", params: ["sessionId"] },
  { name: "storybloq_session_intel", description: "Context usage, expected auto-compaction point with provenance, pressure state (ok/advisory/imperative/compact-needed) and session facts. Works without .story/; sessionId or transcript inspects another session read-only. Also registered in degraded mode", params: ["format?","sessionId?","transcript?","callerModel?","full?","clientTaskId?"] },
  { name: "storybloq_register_subprocess", description: "Register a running subprocess so monitors can tell slow builds from hung agents", params: ["pid","cmd","category","sessionId"] },
  { name: "storybloq_unregister_subprocess", description: "Unregister a subprocess after it completes (idempotent)", params: ["pid","sessionId"] },
  { name: "storybloq_bus_send", description: "Send a task-bound advisory peer message; routes to the sole peer (toRole is deprecated, optional, and ignored)", params: ["endpointId","clientTaskId","threadId?","threadKind?","predecessorThreadId?","toRole?","messageKind","severity","body","refs?","inReplyTo?","idempotencyKey"] },
  { name: "storybloq_bus_redeliver", description: "Redeliver a hop-cap-parked, never-dropped message onto a fresh successor thread; content is always the resolved refused artifact, never caller-supplied", params: ["endpointId","clientTaskId","predecessorThreadId","refusedEntryHash"] },
  { name: "storybloq_bus_poll", description: "Poll a task-bound endpoint mailbox with peer-authority envelopes", params: ["endpointId","clientTaskId","limit?"] },
  { name: "storybloq_bus_ack", description: "Record delivery disposition without resolving canonical work", params: ["endpointId","clientTaskId","messageId","disposition","reason?"] },
  { name: "storybloq_bus_thread_get", description: "Read a participant thread's verified prefix and folded state", params: ["endpointId","clientTaskId","threadId"] },
  { name: "storybloq_bus_thread_update", description: "Park, resolve, or evidence-reopen a participant thread", params: ["endpointId","clientTaskId","threadId","action","reason?","resolution?","evidence?"] },
  { name: "storybloq_node_list", description: "List configured federation nodes in an orchestrator project", params: [] },
  { name: "storybloq_node_init", description: "Initialize .story/ in a federation child node from the orchestrator", params: ["node","type?","language?","force?"] },
  { name: "storybloq_node_add", description: "Add a federation node to an orchestrator project's config", params: ["name","path","stack?","role?","kind?","summary?","dependsOn?","links?"] },
  { name: "storybloq_node_update", description: "Update a federation node's metadata (shallow-merge)", params: ["name","path?","stack?","role?","kind?","summary?","dependsOn?","clearDependsOn?","links?","clearLinks?"] },
  { name: "storybloq_arrangement_coordinate", description: "Record pen-observed duet coordination state; requires the current session and revision. Receipts are attributed evidence, not authentication.", params: ["operation"] },
  { name: "storybloq_arrangement_get", description: "Get a duet/wave arrangement by ID", params: ["id","format?"] },
  { name: "storybloq_arrangement_create", description: "Create a duet/wave charter. identityAnchor must match a client task id (CLAUDE_CODE_SESSION_ID/CODEX_THREAD_ID), never a display name; it is not authentication.", params: ["bounds","parties","onIrreversibleWork","onReversibleWork?"] },
  { name: "storybloq_arrangement_update", description: "Update an arrangement's lifecycle (active/suspended/closed)", params: ["id","lifecycle"] },
  { name: "storybloq_gate_ack_get", description: "Get a duet-mode gate-ack record by ID", params: ["id"] },
  { name: "storybloq_gate_ack_create", description: "Pin acceptance of a declared plan-ack or pre-commit-ack gate. Exactly one of planFile/fromStaged is required; ackRole derives from the arrangement gate.", params: ["arrangement","gate","ticket","planFile?","fromStaged?","codexSessionId?","verdict?","rounds?","deltas?"] },
  { name: "storybloq_gate_ack_contest", description: "Record a contested acknowledgment and its reason; does not reopen the workflow.", params: ["id","reason"] },
  { name: "storybloq_earmark_get", description: "Get the pick-exclusion earmark (if any) on a ticket or issue", params: ["ref","node?"] },
  { name: "storybloq_earmark_reserve", description: "Reserve an item for a duet role pending pickup. Conflicts with another earmark; arrangement is required only if several active arrangements cover the item.", params: ["ref","role","arrangement?","clientTaskId?","node?"] },
  { name: "storybloq_earmark_assign", description: "Place or convert an earmark to a live session matching the arrangement role. Reserved-to-assigned conversion requires the reserver or the arrangement pen.", params: ["ref","to","role","arrangement?","clientTaskId?","node?"] },
  { name: "storybloq_earmark_release", description: "Release an earmark as its reserver or the pen of its authorizing arrangement; no-op when absent.", params: ["ref","arrangement?","clientTaskId?","node?"] },
];

export function handleReference(format: OutputFormat): string {
  return formatReference(COMMANDS, MCP_TOOLS, format);
}
